version: '3.8'

networks:
  new:

services:
  bot:
    networks:
      - new
    build: .
    command: ./bot
    restart: always
    ports:
      - 8001:8001
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=quest_catalog
      - DB_SSL_MODE=disable
    depends_on:
      - db

  rest:
    networks:
      - new
    build: .
    command: ./rest
    restart: always
    ports:
      - 8000:8000
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=quest_catalog
      - DB_SSL_MODE=disable
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    networks:
      new:
        aliases:
          - database
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=quest_catalog
    ports:
      - 5432:5432
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 3s
      retries: 5

volumes:
  db-data: { }